### ISSUE TITLE
Errors prevented startup

### ISSUE THREAD

**Issue by vinaydate** [shadyendless/meteor-typescript-demo#1]
I tried many times, to follow the steps you have described. (With tsc version 1.5 beta and 1.4.1 both). But i get an error message in meteor (1.1.0.2) server saying

=> Modified -- restarting.
   Downloading missing packages              \
Compiling TypeScript os () files...
   Building the application                  |
Compiling TypeScript web.browser () files...
=> Errors prevented startup:

   While building the application:
   G:\Vinay\Projects\TestMeteor\zzz.ts-compiler.ts:1:1:
   module.js:338
   throw err;
   ^
   Error: Cannot find module
   'G:\Vinay\Projects\TestMeteor\node_modules\typescript\bin\tsc'
   at Function.Module._resolveFilename (module.js:336:15)
   at Function.Module._load (module.js:278:25)
   at Function.Module.runMain (module.js:501:10)
   at startup (node.js:129:16)
   at node.js:814:3

=> Your application has errors. Waiting for file change.

**Comment by shadyendless** [comment]
Hey everyone! I have a fix (I think). Assuming that you installed TypeScript for Visual Studio (required for this to work!), type the following in the console (after going to the directory of your project):

`meteor remove meteor add meteortypescript:compiler`

`meteor add meteor add shadyendless:typescript-compiler`
